### ISSUE TITLE
Note on installing dependencies

### ISSUE THREAD

**Issue by eliot-akira** [folkertvanheusden/wav-to-midi#2]
Hello, thank you for making this library open-source, I've enjoyed studying the code.

Just wanted to comment that I followed the install instructions in the README, and ran into a question of missing dependencies (error in the step `cmake ../`). I was able to solve it with

```sh
sudo apt-get install libsndfile1-dev libfftw3-dev
```

**Comment by folkertvanheusden** [comment]
Thanks! Will add the note.
